services:
  # Video Voter Application
  video-voter:
    build: ../server
    depends_on:
      - otel-collector # Depends on otel-collector to be running first
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
    ports:
      - "5000:5000"
    restart: unless-stopped


  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.100.0 # Use `otel/opentelemetry-collector-contrib` to support more backends.
    command:
      - "--config=/conf/otel-collector-config.yaml" # Autodiscovery folder changes between versions. Better to provide explicitly.
    volumes:
      - ./conf/otel-collector-config.yaml:/conf/otel-collector-config.yaml
    ports:
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    restart: unless-stopped
