receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: default
  debug:
    verbosity: detailed

extensions:
  health_check:

service:
    extensions: [health_check]
    pipelines:
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheus]

